# Generated by Django 3.2.16 on 2022-10-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='username_rg',
        ),
        migrations.AlterField(
            model_name='register_user',
            name='fist_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
    ]
